<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IMgg6MEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IMgg6ME' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IMgg6ME'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'selectOptionsQueryHandler' => ['privates', 'App\\User\\Application\\QueryHandler\\SelectOption\\GetSelectOptionsQueryHandler', 'getGetSelectOptionsQueryHandlerService', true],
        ], [
            'selectOptionsQueryHandler' => 'App\\User\\Application\\QueryHandler\\SelectOption\\GetSelectOptionsQueryHandler',
        ]);
    }
}
