<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SpGbT0IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.spGbT0I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.spGbT0I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'registerDTO' => ['privates', 'App\\User\\Domain\\DTO\\User\\RegisterDTO', 'getRegisterDTOService', true],
            'registerUserAction' => ['privates', 'App\\User\\Domain\\Action\\User\\RegisterUserAction', 'getRegisterUserActionService', true],
        ], [
            'registerDTO' => 'App\\User\\Domain\\DTO\\User\\RegisterDTO',
            'registerUserAction' => 'App\\User\\Domain\\Action\\User\\RegisterUserAction',
        ]);
    }
}
