<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_0qSoVF1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.0qSoVF1' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/User/Application/CommandHandler/SelectOptionKind/CreateSelectOptionKindCommandHandler.php';

        return $container->privates['.messenger.handler_descriptor.0qSoVF1'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\User\Application\CommandHandler\SelectOptionKind\CreateSelectOptionKindCommandHandler(($container->privates['App\\User\\Domain\\Service\\SelectOptionKind\\WriterService\\SelectOptionKindWriterService'] ?? $container->load('getSelectOptionKindWriterServiceService'))), ['bus' => 'messenger.bus.default']);
    }
}
