<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XYyd73KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XYyd73K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XYyd73K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'selectOptionKindsQueryHandler' => ['privates', 'App\\User\\Application\\QueryHandler\\SelectOptionKind\\GetSelectOptionKindsQueryHandler', 'getGetSelectOptionKindsQueryHandlerService', true],
        ], [
            'selectOptionKindsQueryHandler' => 'App\\User\\Application\\QueryHandler\\SelectOptionKind\\GetSelectOptionKindsQueryHandler',
        ]);
    }
}
