<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R4BPAQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R4_bPAQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R4_bPAQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'updateDTO' => ['privates', 'App\\User\\Domain\\DTO\\User\\UpdateDTO', 'getUpdateDTOService', true],
            'updateUserAction' => ['privates', 'App\\User\\Domain\\Action\\User\\UpdateUserAction', 'getUpdateUserActionService', true],
        ], [
            'updateDTO' => 'App\\User\\Domain\\DTO\\User\\UpdateDTO',
            'updateUserAction' => 'App\\User\\Domain\\Action\\User\\UpdateUserAction',
        ]);
    }
}
