<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSelectOptionActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Action\SelectOption\CreateSelectOptionAction' shared autowired service.
     *
     * @return \App\User\Domain\Action\SelectOption\CreateSelectOptionAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Action/SelectOption/CreateSelectOptionAction.php';

        return $container->privates['App\\User\\Domain\\Action\\SelectOption\\CreateSelectOptionAction'] = new \App\User\Domain\Action\SelectOption\CreateSelectOptionAction(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
    }
}
