<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteUserActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Action\User\DeleteUserAction' shared autowired service.
     *
     * @return \App\User\Domain\Action\User\DeleteUserAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Action/User/DeleteUserAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/PasswordAuthenticatedUserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserInterface.php';
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Entity/User.php';

        return $container->privates['App\\User\\Domain\\Action\\User\\DeleteUserAction'] = new \App\User\Domain\Action\User\DeleteUserAction(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')), new \App\User\Domain\Entity\User());
    }
}
