<?php

namespace ContainerHPkoESd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Default_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.bus.default.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['messenger.bus.default.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\User\\Application\\Command\\SelectOption\\CreateSelectOptionCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.VQ5W5Ks'] ?? $container->load('get_Messenger_HandlerDescriptor_VQ5W5KsService'));
        }, 1), 'App\\User\\Application\\Command\\SelectOption\\DeleteSelectOptionCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.THsmoTo'] ?? $container->load('get_Messenger_HandlerDescriptor_THsmoToService'));
        }, 1), 'App\\User\\Application\\Command\\SelectOption\\RestoreDeletedSelectOptionCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Eo3H2.A'] ?? $container->load('get_Messenger_HandlerDescriptor_Eo3H2_AService'));
        }, 1), 'App\\User\\Application\\Command\\SelectOption\\UpdateSelectOptionCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.szd6iTw'] ?? $container->load('get_Messenger_HandlerDescriptor_Szd6iTwService'));
        }, 1), 'App\\User\\Application\\Command\\SelectOptionKind\\CreateSelectOptionKindCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.0qSoVF1'] ?? $container->load('get_Messenger_HandlerDescriptor_0qSoVF1Service'));
        }, 1), 'App\\User\\Application\\Command\\SelectOptionKind\\DeleteSelectOptionKindCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.WK.sXjb'] ?? $container->load('get_Messenger_HandlerDescriptor_WK_SXjbService'));
        }, 1), 'App\\User\\Application\\Command\\SelectOptionKind\\UpdateSelectOptionKindCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.8XMalI3'] ?? $container->load('get_Messenger_HandlerDescriptor_8XMalI3Service'));
        }, 1), 'App\\User\\Application\\Command\\User\\ChangeUserPasswordCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.RB8ZxkN'] ?? $container->load('get_Messenger_HandlerDescriptor_RB8ZxkNService'));
        }, 1), 'App\\User\\Application\\Command\\User\\CreateUserCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.cAE0XQX'] ?? $container->load('get_Messenger_HandlerDescriptor_CAE0XQXService'));
        }, 1), 'App\\User\\Application\\Command\\User\\DeleteUserCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.tkAb3fW'] ?? $container->load('get_Messenger_HandlerDescriptor_TkAb3fWService'));
        }, 1), 'App\\User\\Application\\Command\\User\\RegisterUserCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.1QcaYZY'] ?? $container->load('get_Messenger_HandlerDescriptor_1QcaYZYService'));
        }, 1), 'App\\User\\Application\\Command\\User\\RestoreDeletedUserCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.PlrGk7r'] ?? $container->load('get_Messenger_HandlerDescriptor_PlrGk7rService'));
        }, 1), 'App\\User\\Application\\Command\\User\\ToggleActiveCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Le8UR_I'] ?? $container->load('get_Messenger_HandlerDescriptor_Le8URIService'));
        }, 1), 'App\\User\\Application\\Command\\User\\UpdateUserCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.pQ8fnzW'] ?? $container->load('get_Messenger_HandlerDescriptor_PQ8fnzWService'));
        }, 1), 'App\\User\\Application\\Command\\User\\UploadUserAvatarCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.pdkV_4d'] ?? $container->load('get_Messenger_HandlerDescriptor_PdkV4dService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.p4Qvabm'] ?? $container->load('get_Messenger_HandlerDescriptor_P4QvabmService'));
        }, 1)]), false);

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
