framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

            #async: '%env(MESSENGER_TRANSPORT_DSN)%'
            rabbitmq_user_register:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/user_register'
                options:
                    exchange:
                        name: 'user_register' # Nazwa exchange (wymiana)
                        type: direct # Typ exchange (direct, fanout, topic itp.)
        routing:
            #'App\User\Application\Command\RegisterUserCommand': async
            'App\User\Application\Command\User\RegisterUserCommand': rabbitmq_user_register

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
