<?php

namespace ContainerI3Rn32U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SVPDbkNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sVPDbkN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sVPDbkN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'uploadUserAvatarAction' => ['privates', 'App\\User\\Domain\\Action\\User\\UploadUserAvatarAction', 'getUploadUserAvatarActionService', true],
            'uploadUserAvatarDTO' => ['privates', 'App\\User\\Domain\\DTO\\User\\UploadUserAvatarDTO', 'getUploadUserAvatarDTOService', true],
        ], [
            'uploadUserAvatarAction' => 'App\\User\\Domain\\Action\\User\\UploadUserAvatarAction',
            'uploadUserAvatarDTO' => 'App\\User\\Domain\\DTO\\User\\UploadUserAvatarDTO',
        ]);
    }
}
