<?php

namespace ContainerI3Rn32U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E7H_RI7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e7H.rI7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e7H.rI7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'createDTO' => ['privates', 'App\\User\\Domain\\DTO\\User\\CreateDTO', 'getCreateDTOService', true],
            'createUserAction' => ['privates', 'App\\User\\Domain\\Action\\User\\CreateUserAction', 'getCreateUserActionService', true],
        ], [
            'createDTO' => 'App\\User\\Domain\\DTO\\User\\CreateDTO',
            'createUserAction' => 'App\\User\\Domain\\Action\\User\\CreateUserAction',
        ]);
    }
}
