<?php

namespace ContainerI3Rn32U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C5TcDSTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c5TcDST' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c5TcDST'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restoreDeleteAction' => ['privates', 'App\\User\\Domain\\Action\\User\\RestoreDeleteAction', 'getRestoreDeleteActionService', true],
        ], [
            'restoreDeleteAction' => 'App\\User\\Domain\\Action\\User\\RestoreDeleteAction',
        ]);
    }
}
