<?php

namespace ContainerI3Rn32U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Action\User\CreateUserAction' shared autowired service.
     *
     * @return \App\User\Domain\Action\User\CreateUserAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Action/User/CreateUserAction.php';

        return $container->privates['App\\User\\Domain\\Action\\User\\CreateUserAction'] = new \App\User\Domain\Action\User\CreateUserAction(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
    }
}
