<?php

namespace ContainerI3Rn32U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAddressesByUserUUIDQueryHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Application\QueryHandler\Address\GetAddressesByUserUUIDQueryHandler' shared autowired service.
     *
     * @return \App\User\Application\QueryHandler\Address\GetAddressesByUserUUIDQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Application/QueryHandler/Address/GetAddressesByUserUUIDQueryHandler.php';

        return $container->privates['App\\User\\Application\\QueryHandler\\Address\\GetAddressesByUserUUIDQueryHandler'] = new \App\User\Application\QueryHandler\Address\GetAddressesByUserUUIDQueryHandler(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
