<?php

namespace ContainerI3Rn32U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectOptionWriterServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Service\SelectOption\WriterService\SelectOptionWriterService' shared autowired service.
     *
     * @return \App\User\Domain\Service\SelectOption\WriterService\SelectOptionWriterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Service/SelectOption/WriterService/SelectOptionWriterService.php';

        return $container->privates['App\\User\\Domain\\Service\\SelectOption\\WriterService\\SelectOptionWriterService'] = new \App\User\Domain\Service\SelectOption\WriterService\SelectOptionWriterService(($container->privates['App\\User\\Domain\\Repository\\SelectOption\\SelectOptionWriterRepository'] ?? $container->load('getSelectOptionWriterRepositoryService')));
    }
}
