<?php

namespace ContainerI3Rn32U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateSelectOptionActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Action\SelectOption\UpdateSelectOptionAction' shared autowired service.
     *
     * @return \App\User\Domain\Action\SelectOption\UpdateSelectOptionAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Action/SelectOption/UpdateSelectOptionAction.php';
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Entity/SelectOption.php';

        return $container->privates['App\\User\\Domain\\Action\\SelectOption\\UpdateSelectOptionAction'] = new \App\User\Domain\Action\SelectOption\UpdateSelectOptionAction(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')), ($container->privates['App\\User\\Domain\\Entity\\SelectOption'] ??= new \App\User\Domain\Entity\SelectOption()));
    }
}
