<?php

namespace ContainerBZuowu5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YBjwbE7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yBjwbE7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yBjwbE7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'updateUserAction' => ['privates', 'App\\User\\Domain\\Action\\User\\UpdateUserAction', 'getUpdateUserActionService', true],
            'updateValidationRequest' => ['privates', 'App\\User\\Presentation\\Validation\\User\\Update\\UpdateValidationRequest', 'getUpdateValidationRequestService', true],
        ], [
            'updateUserAction' => 'App\\User\\Domain\\Action\\User\\UpdateUserAction',
            'updateValidationRequest' => 'App\\User\\Presentation\\Validation\\User\\Update\\UpdateValidationRequest',
        ]);
    }
}
