<?php

namespace ContainerBZuowu5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserReaderRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Repository\UserReaderRepository' shared autowired service.
     *
     * @return \App\Repository\UserReaderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Repository\\UserReaderRepository'] = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))->getRepository('App\\Entity\\User');
    }
}
