<?php

namespace App\Tests\User\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

class UserControllerTest extends WebTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex(): void
    {
        $token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk5NzMxNzgsImV4cCI6MTcwMDA1OTU3OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20ifQ.h0U9Vbp7X5jHMAasqbHiveRTFwg3Fj32nHhHxD_oV11F3qr3PSOgIdMxyW9whh11FkG1QYSOW8YWLM5K4AvmLZxPpXPrRTyoWtvckAUyV0Cp94f_o-YYPFgL1klA205CulzTHLfUN-oP1U3lNfjVOMT2V5RE8j90LQD3CV5SElNIesxv4D5Jd3bCdts-I5DWCwU7LhRQ9RH8Kbz1gPmE5wJlCx15c8tZA3bRMnlaL-8Z8l0rVK1MsSQK3TWGzlWa1esaDIL07C2Mmger4cavt2H8piMQ43in1JpecMao4FRupbFnTara7A0QcxD0jGExKtRhLEviMX-H9gzCVOJnTA';
        $client = static::createClient();
        $client->setServerParameters([
            'HTTP_AUTHORIZATION' => 'Bearer ' . $token
        ]);
        $client->request('GET', '/api/users');
        $this->assertContains($client->getResponse()->getStatusCode(), [Response::HTTP_OK, Response::HTTP_INTERNAL_SERVER_ERROR]);
        $this->assertJson($client->getResponse()->getContent());
        $this->assertArrayHasKey('data', json_decode($client->getResponse()->getContent(), true));
    }
}