fos_rest:
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
  view:
    view_response_listener: 'force'
