<?php

namespace Container626UDEk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTlZBDtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wTlZBDt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wTlZBDt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersQueryHandler' => ['privates', 'App\\User\\Application\\QueryHandler\\User\\GetUsersQueryHandler', 'getGetUsersQueryHandlerService', true],
        ], [
            'usersQueryHandler' => 'App\\User\\Application\\QueryHandler\\User\\GetUsersQueryHandler',
        ]);
    }
}
