<?php

namespace Container626UDEk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserReaderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Service\ReaderService\UserReaderService' shared autowired service.
     *
     * @return \App\User\Domain\Service\ReaderService\UserReaderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Service/ReaderService/UserReaderService.php';

        return $container->privates['App\\User\\Domain\\Service\\ReaderService\\UserReaderService'] = new \App\User\Domain\Service\ReaderService\UserReaderService(($container->privates['App\\User\\Domain\\Repository\\ReaderRepository\\UserReaderRepository'] ?? $container->load('getUserReaderRepository2Service')));
    }
}
