<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0RfU_NbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0RfU.Nb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0RfU.Nb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'createDTO' => ['privates', 'App\\User\\Domain\\DTO\\SelectOptionKind\\CreateDTO', 'getCreateDTOService', true],
            'createSelectOptionKindAction' => ['privates', 'App\\User\\Domain\\Action\\SelectOptionKind\\CreateSelectOptionKindAction', 'getCreateSelectOptionKindActionService', true],
        ], [
            'createDTO' => 'App\\User\\Domain\\DTO\\SelectOptionKind\\CreateDTO',
            'createSelectOptionKindAction' => 'App\\User\\Domain\\Action\\SelectOptionKind\\CreateSelectOptionKindAction',
        ]);
    }
}
