<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XXHQ9tfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xXHQ9tf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xXHQ9tf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\User\\Presentation\\API\\Address\\UserAddressesController::userAddresses' => ['privates', '.service_locator.UpsMKXz', 'get_ServiceLocator_UpsMKXzService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\CreateSelectOptionKindController::store' => ['privates', '.service_locator.0RfU.Nb', 'get_ServiceLocator_0RfU_NbService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\DeleteSelectOptionKindController::destroy' => ['privates', '.service_locator.ViLYguQ', 'get_ServiceLocator_ViLYguQService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\ListSelectOptionKindController::index' => ['privates', '.service_locator.XYyd73K', 'get_ServiceLocator_XYyd73KService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\RestoreDeletedSelectOptionKindController::restoreDeleted' => ['privates', '.service_locator.COVx17r', 'get_ServiceLocator_COVx17rService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\UpdateSelectOptionKindController::update' => ['privates', '.service_locator.WbFNNjb', 'get_ServiceLocator_WbFNNjbService', true],
            'App\\User\\Presentation\\API\\SelectOption\\CreateSelectOptionController::store' => ['privates', '.service_locator.iA1foEH', 'get_ServiceLocator_IA1foEHService', true],
            'App\\User\\Presentation\\API\\SelectOption\\DeleteSelectOptionController::destroy' => ['privates', '.service_locator.VM_zkd8', 'get_ServiceLocator_VMZkd8Service', true],
            'App\\User\\Presentation\\API\\SelectOption\\ListSelectOptionController::index' => ['privates', '.service_locator.IMgg6ME', 'get_ServiceLocator_IMgg6MEService', true],
            'App\\User\\Presentation\\API\\SelectOption\\RestoreDeletedSelectOptionController::restoreDeleted' => ['privates', '.service_locator.l6qnxpx', 'get_ServiceLocator_L6qnxpxService', true],
            'App\\User\\Presentation\\API\\SelectOption\\UpdateSelectOptionController::update' => ['privates', '.service_locator.X7LK0uw', 'get_ServiceLocator_X7LK0uwService', true],
            'App\\User\\Presentation\\API\\User\\ChangeUserPasswordController::changePassword' => ['privates', '.service_locator.QYW0vF4', 'get_ServiceLocator_QYW0vF4Service', true],
            'App\\User\\Presentation\\API\\User\\CreateUserController::store' => ['privates', '.service_locator.e7H.rI7', 'get_ServiceLocator_E7H_RI7Service', true],
            'App\\User\\Presentation\\API\\User\\DeleteUserController::destroy' => ['privates', '.service_locator.Za3oEHn', 'get_ServiceLocator_Za3oEHnService', true],
            'App\\User\\Presentation\\API\\User\\ListUserController::index' => ['privates', '.service_locator.wTlZBDt', 'get_ServiceLocator_WTlZBDtService', true],
            'App\\User\\Presentation\\API\\User\\RegisterUserController::register' => ['privates', '.service_locator.spGbT0I', 'get_ServiceLocator_SpGbT0IService', true],
            'App\\User\\Presentation\\API\\User\\RestoreDeletedUserController::restoreDeleted' => ['privates', '.service_locator.c5TcDST', 'get_ServiceLocator_C5TcDSTService', true],
            'App\\User\\Presentation\\API\\User\\ToggleActiveUserController::toggleActive' => ['privates', '.service_locator.n9paums', 'get_ServiceLocator_N9paumsService', true],
            'App\\User\\Presentation\\API\\User\\UpdateUserController::update' => ['privates', '.service_locator.R4_bPAQ', 'get_ServiceLocator_R4BPAQService', true],
            'App\\User\\Presentation\\API\\User\\UploadUserAvatarController::store' => ['privates', '.service_locator.sVPDbkN', 'get_ServiceLocator_SVPDbkNService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\User\\Presentation\\API\\Address\\UserAddressesController:userAddresses' => ['privates', '.service_locator.UpsMKXz', 'get_ServiceLocator_UpsMKXzService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\CreateSelectOptionKindController:store' => ['privates', '.service_locator.0RfU.Nb', 'get_ServiceLocator_0RfU_NbService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\DeleteSelectOptionKindController:destroy' => ['privates', '.service_locator.ViLYguQ', 'get_ServiceLocator_ViLYguQService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\ListSelectOptionKindController:index' => ['privates', '.service_locator.XYyd73K', 'get_ServiceLocator_XYyd73KService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\RestoreDeletedSelectOptionKindController:restoreDeleted' => ['privates', '.service_locator.COVx17r', 'get_ServiceLocator_COVx17rService', true],
            'App\\User\\Presentation\\API\\SelectOptionKind\\UpdateSelectOptionKindController:update' => ['privates', '.service_locator.WbFNNjb', 'get_ServiceLocator_WbFNNjbService', true],
            'App\\User\\Presentation\\API\\SelectOption\\CreateSelectOptionController:store' => ['privates', '.service_locator.iA1foEH', 'get_ServiceLocator_IA1foEHService', true],
            'App\\User\\Presentation\\API\\SelectOption\\DeleteSelectOptionController:destroy' => ['privates', '.service_locator.VM_zkd8', 'get_ServiceLocator_VMZkd8Service', true],
            'App\\User\\Presentation\\API\\SelectOption\\ListSelectOptionController:index' => ['privates', '.service_locator.IMgg6ME', 'get_ServiceLocator_IMgg6MEService', true],
            'App\\User\\Presentation\\API\\SelectOption\\RestoreDeletedSelectOptionController:restoreDeleted' => ['privates', '.service_locator.l6qnxpx', 'get_ServiceLocator_L6qnxpxService', true],
            'App\\User\\Presentation\\API\\SelectOption\\UpdateSelectOptionController:update' => ['privates', '.service_locator.X7LK0uw', 'get_ServiceLocator_X7LK0uwService', true],
            'App\\User\\Presentation\\API\\User\\ChangeUserPasswordController:changePassword' => ['privates', '.service_locator.QYW0vF4', 'get_ServiceLocator_QYW0vF4Service', true],
            'App\\User\\Presentation\\API\\User\\CreateUserController:store' => ['privates', '.service_locator.e7H.rI7', 'get_ServiceLocator_E7H_RI7Service', true],
            'App\\User\\Presentation\\API\\User\\DeleteUserController:destroy' => ['privates', '.service_locator.Za3oEHn', 'get_ServiceLocator_Za3oEHnService', true],
            'App\\User\\Presentation\\API\\User\\ListUserController:index' => ['privates', '.service_locator.wTlZBDt', 'get_ServiceLocator_WTlZBDtService', true],
            'App\\User\\Presentation\\API\\User\\RegisterUserController:register' => ['privates', '.service_locator.spGbT0I', 'get_ServiceLocator_SpGbT0IService', true],
            'App\\User\\Presentation\\API\\User\\RestoreDeletedUserController:restoreDeleted' => ['privates', '.service_locator.c5TcDST', 'get_ServiceLocator_C5TcDSTService', true],
            'App\\User\\Presentation\\API\\User\\ToggleActiveUserController:toggleActive' => ['privates', '.service_locator.n9paums', 'get_ServiceLocator_N9paumsService', true],
            'App\\User\\Presentation\\API\\User\\UpdateUserController:update' => ['privates', '.service_locator.R4_bPAQ', 'get_ServiceLocator_R4BPAQService', true],
            'App\\User\\Presentation\\API\\User\\UploadUserAvatarController:store' => ['privates', '.service_locator.sVPDbkN', 'get_ServiceLocator_SVPDbkNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\User\\Presentation\\API\\Address\\UserAddressesController::userAddresses' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\CreateSelectOptionKindController::store' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\DeleteSelectOptionKindController::destroy' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\ListSelectOptionKindController::index' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\RestoreDeletedSelectOptionKindController::restoreDeleted' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\UpdateSelectOptionKindController::update' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\CreateSelectOptionController::store' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\DeleteSelectOptionController::destroy' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\ListSelectOptionController::index' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\RestoreDeletedSelectOptionController::restoreDeleted' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\UpdateSelectOptionController::update' => '?',
            'App\\User\\Presentation\\API\\User\\ChangeUserPasswordController::changePassword' => '?',
            'App\\User\\Presentation\\API\\User\\CreateUserController::store' => '?',
            'App\\User\\Presentation\\API\\User\\DeleteUserController::destroy' => '?',
            'App\\User\\Presentation\\API\\User\\ListUserController::index' => '?',
            'App\\User\\Presentation\\API\\User\\RegisterUserController::register' => '?',
            'App\\User\\Presentation\\API\\User\\RestoreDeletedUserController::restoreDeleted' => '?',
            'App\\User\\Presentation\\API\\User\\ToggleActiveUserController::toggleActive' => '?',
            'App\\User\\Presentation\\API\\User\\UpdateUserController::update' => '?',
            'App\\User\\Presentation\\API\\User\\UploadUserAvatarController::store' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\User\\Presentation\\API\\Address\\UserAddressesController:userAddresses' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\CreateSelectOptionKindController:store' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\DeleteSelectOptionKindController:destroy' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\ListSelectOptionKindController:index' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\RestoreDeletedSelectOptionKindController:restoreDeleted' => '?',
            'App\\User\\Presentation\\API\\SelectOptionKind\\UpdateSelectOptionKindController:update' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\CreateSelectOptionController:store' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\DeleteSelectOptionController:destroy' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\ListSelectOptionController:index' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\RestoreDeletedSelectOptionController:restoreDeleted' => '?',
            'App\\User\\Presentation\\API\\SelectOption\\UpdateSelectOptionController:update' => '?',
            'App\\User\\Presentation\\API\\User\\ChangeUserPasswordController:changePassword' => '?',
            'App\\User\\Presentation\\API\\User\\CreateUserController:store' => '?',
            'App\\User\\Presentation\\API\\User\\DeleteUserController:destroy' => '?',
            'App\\User\\Presentation\\API\\User\\ListUserController:index' => '?',
            'App\\User\\Presentation\\API\\User\\RegisterUserController:register' => '?',
            'App\\User\\Presentation\\API\\User\\RestoreDeletedUserController:restoreDeleted' => '?',
            'App\\User\\Presentation\\API\\User\\ToggleActiveUserController:toggleActive' => '?',
            'App\\User\\Presentation\\API\\User\\UpdateUserController:update' => '?',
            'App\\User\\Presentation\\API\\User\\UploadUserAvatarController:store' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
