<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Za3oEHnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Za3oEHn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Za3oEHn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deleteUserAction' => ['privates', 'App\\User\\Domain\\Action\\User\\DeleteUserAction', 'getDeleteUserActionService', true],
        ], [
            'deleteUserAction' => 'App\\User\\Domain\\Action\\User\\DeleteUserAction',
        ]);
    }
}
