<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_COVx17rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.COVx17r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.COVx17r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restoreDeletedSelectOptionKindAction' => ['privates', 'App\\User\\Domain\\Action\\SelectOptionKind\\RestoreDeletedSelectOptionKindAction', 'getRestoreDeletedSelectOptionKindActionService', true],
        ], [
            'restoreDeletedSelectOptionKindAction' => 'App\\User\\Domain\\Action\\SelectOptionKind\\RestoreDeletedSelectOptionKindAction',
        ]);
    }
}
