<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IA1foEHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iA1foEH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iA1foEH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'createDTO' => ['privates', 'App\\User\\Domain\\DTO\\SelectOption\\CreateDTO', 'getCreateDTO3Service', true],
            'createSelectOptionAction' => ['privates', 'App\\User\\Domain\\Action\\SelectOption\\CreateSelectOptionAction', 'getCreateSelectOptionActionService', true],
        ], [
            'createDTO' => 'App\\User\\Domain\\DTO\\SelectOption\\CreateDTO',
            'createSelectOptionAction' => 'App\\User\\Domain\\Action\\SelectOption\\CreateSelectOptionAction',
        ]);
    }
}
