<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UpsMKXzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UpsMKXz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UpsMKXz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'getAddressesByUserUUIDQueryHandler' => ['privates', 'App\\User\\Application\\QueryHandler\\Address\\GetAddressesByUserUUIDQueryHandler', 'getGetAddressesByUserUUIDQueryHandlerService', true],
        ], [
            'getAddressesByUserUUIDQueryHandler' => 'App\\User\\Application\\QueryHandler\\Address\\GetAddressesByUserUUIDQueryHandler',
        ]);
    }
}
