<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ViLYguQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ViLYguQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ViLYguQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deleteSelectOptionKindAction' => ['privates', 'App\\User\\Domain\\Action\\SelectOptionKind\\DeleteSelectOptionKindAction', 'getDeleteSelectOptionKindActionService', true],
        ], [
            'deleteSelectOptionKindAction' => 'App\\User\\Domain\\Action\\SelectOptionKind\\DeleteSelectOptionKindAction',
        ]);
    }
}
