<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateDTO2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\DTO\User\CreateDTO' shared autowired service.
     *
     * @return \App\User\Domain\DTO\User\CreateDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/prugala/symfony-request-dto/src/Dto/RequestDtoInterface.php';
        include_once \dirname(__DIR__, 4).'/src/User/Domain/DTO/User/CreateDTO.php';

        return $container->privates['App\\User\\Domain\\DTO\\User\\CreateDTO'] = new \App\User\Domain\DTO\User\CreateDTO();
    }
}
