<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteSelectOptionKindControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\User\Presentation\API\SelectOptionKind\DeleteSelectOptionKindController' shared autowired service.
     *
     * @return \App\User\Presentation\API\SelectOptionKind\DeleteSelectOptionKindController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/User/Presentation/API/SelectOptionKind/DeleteSelectOptionKindController.php';

        $container->services['App\\User\\Presentation\\API\\SelectOptionKind\\DeleteSelectOptionKindController'] = $instance = new \App\User\Presentation\API\SelectOptionKind\DeleteSelectOptionKindController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['App\\User\\Domain\\Repository\\SelectOptionKind\\ReaderRepository\\SelectOptionKindReaderRepository'] ?? $container->load('getSelectOptionKindReaderRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\User\\Presentation\\API\\SelectOptionKind\\DeleteSelectOptionKindController', $container));

        return $instance;
    }
}
