<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestDtoArgumentResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.value_resolver.Prugala\RequestDto\ArgumentResolver\RequestDtoArgumentResolver' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/prugala/symfony-request-dto/src/ArgumentResolver/RequestDtoArgumentResolver.php';

        return $container->privates['.debug.value_resolver.Prugala\\RequestDto\\ArgumentResolver\\RequestDtoArgumentResolver'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Prugala\RequestDto\ArgumentResolver\RequestDtoArgumentResolver(($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['serializer'] ?? self::getSerializerService($container))), ($container->privates['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
