<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectOptionKindWriterServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Service\SelectOptionKind\WriterService\SelectOptionKindWriterService' shared autowired service.
     *
     * @return \App\User\Domain\Service\SelectOptionKind\WriterService\SelectOptionKindWriterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Service/SelectOptionKind/WriterService/SelectOptionKindWriterService.php';

        return $container->privates['App\\User\\Domain\\Service\\SelectOptionKind\\WriterService\\SelectOptionKindWriterService'] = new \App\User\Domain\Service\SelectOptionKind\WriterService\SelectOptionKindWriterService(($container->privates['App\\User\\Domain\\Repository\\SelectOptionKind\\WriterRepository\\SelectOptionKindWriterRepository'] ?? $container->load('getSelectOptionKindWriterRepositoryService')));
    }
}
