<?php

namespace ContainerVhmgMz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateSelectOptionKindActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Action\SelectOptionKind\UpdateSelectOptionKindAction' shared autowired service.
     *
     * @return \App\User\Domain\Action\SelectOptionKind\UpdateSelectOptionKindAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Action/SelectOptionKind/UpdateSelectOptionKindAction.php';
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Entity/SelectOptionKind.php';

        return $container->privates['App\\User\\Domain\\Action\\SelectOptionKind\\UpdateSelectOptionKindAction'] = new \App\User\Domain\Action\SelectOptionKind\UpdateSelectOptionKindAction(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')), ($container->privates['App\\User\\Domain\\Entity\\SelectOptionKind'] ??= new \App\User\Domain\Entity\SelectOptionKind()));
    }
}
