<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTyvOGFW\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTyvOGFW/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTyvOGFW.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTyvOGFW\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerTyvOGFW\App_KernelTestDebugContainer([
    'container.build_hash' => 'TyvOGFW',
    'container.build_id' => '13777362',
    'container.build_time' => 1698083058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTyvOGFW');
