<?php

namespace Container5M1sz8s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Szd6iTwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.szd6iTw' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/User/Application/CommandHandler/SelectOption/UpdateSelectOptionCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Entity/SelectOption.php';

        return $container->privates['.messenger.handler_descriptor.szd6iTw'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\User\Application\CommandHandler\SelectOption\UpdateSelectOptionCommandHandler(($container->privates['App\\User\\Domain\\Service\\SelectOption\\WriterService\\SelectOptionWriterService'] ?? $container->load('getSelectOptionWriterServiceService')), ($container->privates['App\\User\\Domain\\Entity\\SelectOption'] ??= new \App\User\Domain\Entity\SelectOption())), ['bus' => 'messenger.bus.default']);
    }
}
