<?php

namespace Container5M1sz8s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VMZkd8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VM_zkd8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VM_zkd8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deleteSelectOptionAction' => ['privates', 'App\\User\\Domain\\Action\\SelectOption\\DeleteSelectOptionAction', 'getDeleteSelectOptionActionService', true],
        ], [
            'deleteSelectOptionAction' => 'App\\User\\Domain\\Action\\SelectOption\\DeleteSelectOptionAction',
        ]);
    }
}
