<?php

namespace Container5M1sz8s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectOptionReaderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Service\SelectOption\ReaderService\SelectOptionReaderService' shared autowired service.
     *
     * @return \App\User\Domain\Service\SelectOption\ReaderService\SelectOptionReaderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Service/SelectOption/ReaderService/SelectOptionReaderService.php';

        return $container->privates['App\\User\\Domain\\Service\\SelectOption\\ReaderService\\SelectOptionReaderService'] = new \App\User\Domain\Service\SelectOption\ReaderService\SelectOptionReaderService(($container->privates['App\\User\\Domain\\Repository\\SelectOption\\ReaderRepository\\SelectOptionReaderRepository'] ?? $container->load('getSelectOptionReaderRepositoryService')));
    }
}
