controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_controllers:
    resource:
        path: ../src/User/Presentation/API/User
        namespace: App\User\Presentation\API\User
    type: annotation
address_controllers:
    resource:
        path: ../src/User/Presentation/API/Address
        namespace: App\User\Presentation\API\Address
    type: annotation
select_option_controllers:
    resource:
        path: ../src/User/Presentation/API/SelectOption
        namespace: App\User\Presentation\API\SelectOption
    type: annotation
select_option_kind_controllers:
    resource:
        path: ../src/User/Presentation/API/SelectOptionKind
        namespace: App\User\Presentation\API\SelectOptionKind
    type: annotation
api_login_check:
    path: /api/login_check

