# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    #http_kernel.controller.argument_value_resolver.request.class: App\tests\User\Controller\UserControllerTest

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #App\Category\Presentation\API\CategoryController:
        #tags: ['controller.service_arguments']
    #App\User\Presentation\API\UserController:
        #tags: ['controller.service_arguments']

    App\Repository\UserReaderRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - App\Entity\User
        public: true
    App\User\Application\CommandHandler\User\RegisterUserCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\User\CreateUserCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\User\UpdateUserCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\User\DeleteUserCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\User\RestoreDeletedUserCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\User\ToggleActiveCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\User\UploadUserAvatarCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\User\ChangeUserPasswordCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOption\CreateSelectOptionCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOption\UpdateSelectOptionCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOption\DeleteSelectOptionCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOption\RestoreDeletedSelectOptionCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOptionKind\CreateSelectOptionKindCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOptionKind\UpdateSelectOptionKindCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOptionKind\DeleteSelectOptionKindCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\User\Application\CommandHandler\SelectOptionKind\RestoreDeletedSelectOptionKindCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]