<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0dgqFkeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.0dgqFke' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0dgqFke'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'createUserAction' => ['privates', 'App\\User\\Domain\\Action\\User\\CreateUserAction', 'getCreateUserActionService', true],
            'createValidationRequest' => ['privates', 'App\\User\\Presentation\\Validation\\User\\Create\\CreateValidationRequest', 'getCreateValidationRequestService', true],
        ], [
            'createUserAction' => 'App\\User\\Domain\\Action\\User\\CreateUserAction',
            'createValidationRequest' => 'App\\User\\Presentation\\Validation\\User\\Create\\CreateValidationRequest',
        ]);
    }
}
