<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qpu31PcService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qpu31Pc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qpu31Pc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messenger.transport.rabbitmq_user_register' => ['privates', 'messenger.transport.rabbitmq_user_register', 'getMessenger_Transport_RabbitmqUserRegisterService', true],
            'rabbitmq_user_register' => ['privates', 'messenger.transport.rabbitmq_user_register', 'getMessenger_Transport_RabbitmqUserRegisterService', true],
        ], [
            'messenger.transport.rabbitmq_user_register' => '?',
            'rabbitmq_user_register' => '?',
        ]);
    }
}
