<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Category\Presentation\API\CategoryController' shared autowired service.
     *
     * @return \App\Category\Presentation\API\CategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Category/Presentation/API/CategoryController.php';

        return $container->services['App\\Category\\Presentation\\API\\CategoryController'] = new \App\Category\Presentation\API\CategoryController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
