<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteUserCommandHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\User\Application\CommandHandler\User\DeleteUserCommandHandler' shared autowired service.
     *
     * @return \App\User\Application\CommandHandler\User\DeleteUserCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Application/CommandHandler/User/DeleteUserCommandHandler.php';

        return $container->privates['App\\User\\Application\\CommandHandler\\User\\DeleteUserCommandHandler'] = new \App\User\Application\CommandHandler\User\DeleteUserCommandHandler(($container->privates['App\\User\\Domain\\Service\\WriterService\\UserWriterService'] ?? $container->load('getUserWriterServiceService')));
    }
}
