<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailUniqueValidator3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\User\Presentation\Validation\User\Update\Email\EmailUniqueValidator' shared autowired service.
     *
     * @return \App\User\Presentation\Validation\User\Update\Email\EmailUniqueValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/User/Presentation/Validation/User/Update/Email/EmailUniqueValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Request.php';
        include_once \dirname(__DIR__, 4).'/src/User/Presentation/Request/User/UpdateRequest.php';

        return $container->privates['App\\User\\Presentation\\Validation\\User\\Update\\Email\\EmailUniqueValidator'] = new \App\User\Presentation\Validation\User\Update\Email\EmailUniqueValidator(($container->privates['App\\User\\Domain\\Service\\ReaderService\\UserReaderService'] ?? $container->load('getUserReaderServiceService')), ($container->privates['App\\User\\Presentation\\Request\\User\\UpdateRequest'] ??= new \App\User\Presentation\Request\User\UpdateRequest()));
    }
}
