<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterValidationRequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\User\Presentation\Validation\User\Register\RegisterValidationRequest' shared autowired service.
     *
     * @return \App\User\Presentation\Validation\User\Register\RegisterValidationRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Presentation/Validation/User/Register/RegisterValidationRequest.php';

        return $container->privates['App\\User\\Presentation\\Validation\\User\\Register\\RegisterValidationRequest'] = new \App\User\Presentation\Validation\User\Register\RegisterValidationRequest(($container->privates['App\\User\\Presentation\\Validation\\User\\Register\\RegisterValidation'] ?? $container->load('getRegisterValidationService')));
    }
}
