<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterUserCommandHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\User\Application\CommandHandler\User\RegisterUserCommandHandler' shared autowired service.
     *
     * @return \App\User\Application\CommandHandler\User\RegisterUserCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Application/CommandHandler/User/RegisterUserCommandHandler.php';

        return $container->privates['App\\User\\Application\\CommandHandler\\User\\RegisterUserCommandHandler'] = new \App\User\Application\CommandHandler\User\RegisterUserCommandHandler(($container->privates['App\\User\\Domain\\Service\\WriterService\\UserWriterService'] ?? $container->load('getUserWriterServiceService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
