<?php

namespace ContainerTyvOGFW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterUserActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\User\Domain\Action\User\RegisterUserAction' shared autowired service.
     *
     * @return \App\User\Domain\Action\User\RegisterUserAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Action/User/RegisterUserAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Request.php';
        include_once \dirname(__DIR__, 4).'/src/User/Presentation/Request/User/RegisterRequest.php';

        return $container->privates['App\\User\\Domain\\Action\\User\\RegisterUserAction'] = new \App\User\Domain\Action\User\RegisterUserAction(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')), ($container->privates['App\\User\\Presentation\\Request\\User\\RegisterRequest'] ??= new \App\User\Presentation\Request\User\RegisterRequest()));
    }
}
