<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWmd9cjM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWmd9cjM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWmd9cjM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWmd9cjM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWmd9cjM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wmd9cjM',
    'container.build_id' => 'fccacb18',
    'container.build_time' => 1711206374,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWmd9cjM');
