<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBZuowu5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBZuowu5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBZuowu5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBZuowu5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBZuowu5\App_KernelDevDebugContainer([
    'container.build_hash' => 'BZuowu5',
    'container.build_id' => 'e1275758',
    'container.build_time' => 1698083417,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBZuowu5');
