<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_test_number' => [[], ['_controller' => 'App\\Controller\\TestController::number'], [], [['text', '/test/number']], [], [], []],
    'api.categories.index' => [[], ['_controller' => 'App\\Category\\Presentation\\API\\CategoryController::index'], [], [['text', '/api/categories']], [], [], []],
    'api.categories.show' => [['id'], ['_controller' => 'App\\Category\\Presentation\\API\\CategoryController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/categories']], [], [], []],
    'api.categories.create' => [[], ['_controller' => 'App\\Category\\Presentation\\API\\CategoryController::create'], [], [['text', '/api/categories/']], [], [], []],
    'api.categories.update' => [['id'], ['_controller' => 'App\\Category\\Presentation\\API\\CategoryController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/categories']], [], [], []],
    'api.categories.delete' => [['id'], ['_controller' => 'App\\Category\\Presentation\\API\\CategoryController::destroy'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/categories']], [], [], []],
    'api.users.index' => [[], ['_controller' => 'App\\User\\Presentation\\API\\UserController::index'], [], [['text', '/api/users']], [], [], []],
    'api.users.show' => [['uuid'], ['_controller' => 'App\\User\\Presentation\\API\\UserController::show'], [], [['variable', '/', '[^/]++', 'uuid', true], ['text', '/api/users']], [], [], []],
    'api.users.store' => [[], ['_controller' => 'App\\User\\Presentation\\API\\UserController::store'], [], [['text', '/api/users']], [], [], []],
    'api.users.update' => [['uuid'], ['_controller' => 'App\\User\\Presentation\\API\\UserController::update'], [], [['variable', '/', '[^/]++', 'uuid', true], ['text', '/api/users']], [], [], []],
    'api.users.register' => [[], ['_controller' => 'App\\User\\Presentation\\API\\UserController::register'], [], [['text', '/api/users/register']], [], [], []],
    'api.users.destroy' => [['uuid'], ['_controller' => 'App\\User\\Presentation\\API\\UserController::destroy'], [], [['variable', '/', '[^/]++', 'uuid', true], ['text', '/api/users']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
];
