controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
movies_controllers:
    resource:
        path: ../src/Movie/Presentation/API/
        namespace: App\Movie\Presentation\API\
    type: annotation

